version: '3.6'

services:
  php:
    build: ./infra/php
    volumes:
    - ./www:/var/www/html

  front:
    build: ./infra/nginx
    ports:
    - 80:80
    volumes:
    - ./www:/var/www/html
    - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf